// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectWebsite
{
    public partial class ServiceTransactions
    {
        public int TransactionId { get; set; }
        public int BuyerId { get; set; }
        public int SellerId { get; set; }
        public int ServiceId { get; set; }
        public DateTime TransactionDate { get; set; }

        public virtual Users Buyer { get; set; }
        public virtual Users Seller { get; set; }
    }
}