// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectWebsite
{
    public partial class Services
    {
        public int UserId { get; set; }
        public int ServiceId { get; set; }
        public string ServiceName { get; set; }
        public string Description { get; set; }
        public double Rate { get; set; }
        
        public bool IsBought { get; set; }

        public virtual Users User { get; set; }
    }
}